export const ADD_DATA = "ADD_DATA"
export const SET_CONFIG = "SET_CONFIG"
export const SET_BANNER_CONTENT = "SET_BANNER_CONTENT"
export const SET_BANNER_DETAIL = "SET_BANNER_DETAIL"
export const SET_BANNER_STYLE = "SET_BANNER_STYLE"

export const DEAL_VIEW_COMPONENT = "DEAL_VIEW_COMPONENT"
